### ISSUE TITLE
Implement Call of Cthulhu dice rolling

### ISSUE THREAD

**Issue by ProjectMoon** [ProjectMoon/matrix-dicebot#7]
Once we find out the rules for it.

**Comment by Zoinker** [comment]
Regular skill/characteristic roll:
* Roll 1d100 (1d% + 1d10)
* argument: Skill/characteristic value
* results
  * Roll > value: Failure
  * Roll >=96 | value < 50 OR Roll = 100: Fumble
  * Roll <= value: Success
  * Roll <= value/2: Hard Success (fractions rounded down)
  * Roll <= value/5: Extreme Success (--''--)
  * Roll = 1: Critical Success
* Bonus die: add 1 or 2 d%, pick lowest d%
* Penalty die: add 1 or 2 d%, pick highest d%

Advancement roll: (For increasing skills)
* Roll 1d100 (1d% + 1d10)
* Argument: Skill value (characteristics in some cases)
 * Results:
  * Roll <= value: Failure
  * Roll > value: Success. Roll 1d10 and add it to your skill.
